-- ============================================================
-- PIRACY REPORTING SYSTEM - COMPLETE DATABASE SCHEMA v3
-- Primary keys use CHAR(36) UUID (requires MySQL 8.0.13+)
-- Run: mysql -u piracy_user -p piracy_reporting < database/schema.sql
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- USERS & AUTH
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id                    CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  first_name            VARCHAR(100) NOT NULL,
  last_name             VARCHAR(100) DEFAULT '',
  username              VARCHAR(100) NOT NULL UNIQUE,
  email                 VARCHAR(255) NOT NULL UNIQUE,
  password              VARCHAR(64)  NOT NULL COMMENT 'SHA-256 hex',
  role                  ENUM('superadmin','admin','user') NOT NULL DEFAULT 'user',
  is_active             TINYINT(1)   NOT NULL DEFAULT 1,
  status                ENUM('pending','active','rejected') NOT NULL DEFAULT 'active',
  password_expires_at   DATETIME,
  last_login            DATETIME,
  created_at            DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_role        (role),
  INDEX idx_active      (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- MODULES (registry — one row per Excel sheet)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS modules (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  name        VARCHAR(150) NOT NULL UNIQUE COMMENT 'Exact Excel sheet tab name',
  label       VARCHAR(150) NOT NULL,
  route       VARCHAR(100) NOT NULL UNIQUE,
  db_table    VARCHAR(100) NOT NULL,
  icon        VARCHAR(50),
  color       VARCHAR(30),
  is_active   TINYINT(1) NOT NULL DEFAULT 1,
  sort_order  INT DEFAULT 0,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO modules (name, label, route, db_table, icon, color, sort_order) VALUES
('Social Media',                  'Social Media',                    '/social-media',                 'social_media',                   'fa-share-nodes',      'blue',   1),
('Marketplace',                   'Marketplace',                     '/marketplace',                  'marketplace',                    'fa-store',            'orange', 2),
('Unauthorized Search Result',    'Unauthorized Search Result',      '/unauthorized-search',          'unauthorized_search_result',     'fa-magnifying-glass', 'red',    3),
('Ads Tutorials- Social Media',   'Ads Tutorials - Social Media',    '/ads-social-media',             'ads_tutorials_social_media',     'fa-bullhorn',         'blue',   4),
('Password Sharing-Social Med.',  'Password Sharing - Social Media', '/password-sharing-social',      'password_sharing_social_media',  'fa-lock',             'orange', 5),
('Password Sharing-Marketplace',  'Password Sharing - Marketplace',  '/password-sharing-marketplace', 'password_sharing_marketplace',   'fa-cart-shopping',    'purple', 6),
('IPTV & Apps - Internet',        'IPTV & Apps - Internet',          '/iptv-internet',                'iptv_apps_internet',             'fa-globe',            'teal',   7),
('IPTV & Apps - Apps',            'IPTV & Apps - Apps',              '/iptv-apps',                    'iptv_apps_apps',                 'fa-mobile-screen',    'green',  8),
('IPTV & Apps - Social Media',    'IPTV & Apps - Social Media',      '/iptv-social',                  'iptv_apps_social_media',         'fa-share-nodes',      'pink',   9),
('IPTV & Apps - Marketplace',     'IPTV & Apps - Marketplace',       '/iptv-marketplace',             'iptv_apps_marketplace',          'fa-store',            'yellow', 10),
('IPTV & Apps - Meta Ads',        'IPTV & Apps - Meta Ads',          '/iptv-meta-ads',                'iptv_apps_meta_ads',             'fa-tv',               'indigo', 11);

-- ────────────────────────────────────────────────────────────
-- USER MODULE PERMISSIONS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_module_permissions (
  id               CHAR(36)   NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  user_id          CHAR(36)   NOT NULL,
  module_id        CHAR(36)   NOT NULL,
  can_view         TINYINT(1) NOT NULL DEFAULT 0,
  can_upload       TINYINT(1) NOT NULL DEFAULT 0,
  can_edit         TINYINT(1) NOT NULL DEFAULT 0,
  can_delete       TINYINT(1) NOT NULL DEFAULT 0,
  can_bulk_update  TINYINT(1) NOT NULL DEFAULT 0,
  can_export       TINYINT(1) NOT NULL DEFAULT 0,
  granted_by       CHAR(36),
  granted_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_module (user_id, module_id),
  INDEX idx_user_id   (user_id),
  INDEX idx_module_id (module_id),
  FOREIGN KEY (user_id)   REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- USER ACTIVITY LOG
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_activity (
  id             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  user_id        CHAR(36)     NOT NULL,
  user_name      VARCHAR(100) NOT NULL,
  action         VARCHAR(100) NOT NULL,
  sheet_name     VARCHAR(150),
  file_name      VARCHAR(255),
  records_count  INT DEFAULT 0,
  record_id      CHAR(36),
  ip_address     VARCHAR(45),
  details        TEXT,
  created_at     DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user    (user_id),
  INDEX idx_action  (action),
  INDEX idx_sheet   (sheet_name),
  INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- USER PREFERENCES
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_preferences (
  user_id      CHAR(36)    NOT NULL PRIMARY KEY,
  theme        VARCHAR(30) DEFAULT 'blue',
  mode         VARCHAR(10) DEFAULT 'dark',
  custom_color VARCHAR(7)  DEFAULT '#3b82f6',
  updated_at   DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- REMOVAL STATUS HISTORY (optional audit trail)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS removal_status_history (
  id                CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  record_id         CHAR(36)     NOT NULL,
  sheet_name        VARCHAR(150),
  table_name        VARCHAR(100),
  old_status        VARCHAR(100),
  new_status        VARCHAR(100),
  old_removal_time  DATETIME,
  new_removal_time  DATETIME,
  updated_by        CHAR(36),
  created_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_record  (record_id),
  INDEX idx_table   (table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- EMAIL CONFIGURATION
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_config (
  id            CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  purpose       VARCHAR(64)  NOT NULL DEFAULT 'notification',
  label         VARCHAR(128) NOT NULL DEFAULT 'Default',
  smtp_host     VARCHAR(255) NOT NULL DEFAULT 'smtp.gmail.com',
  smtp_port     INT          NOT NULL DEFAULT 587,
  smtp_secure   TINYINT(1)   NOT NULL DEFAULT 0,
  smtp_user     VARCHAR(255) NOT NULL,
  smtp_pass     VARCHAR(255) NOT NULL,
  from_name     VARCHAR(128) NOT NULL DEFAULT 'API Monitoring System',
  from_email    VARCHAR(255) NOT NULL,
  is_active     TINYINT(1)   NOT NULL DEFAULT 1,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- MODULE TABLES
-- NOTE: unique URL columns use a generated STORED hash column
-- so TEXT fields can have a UNIQUE index via SHA2(col,256).
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. Unauthorized Search Result  →  unique: linking_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS unauthorized_search_result (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  date_of_identification         DATETIME,
  title                          VARCHAR(512),
  copyright_owner                VARCHAR(512),
  linking_url                    TEXT,
  linking_url_hash               VARCHAR(64) AS (SHA2(linking_url, 256)) STORED,
  website                        VARCHAR(512),
  pirate_website_brand           VARCHAR(255),
  sw_data_month                  VARCHAR(50),
  sw_monthly_traffic             BIGINT,
  traffic_from_search_engines    BIGINT,
  sw_global_rank                 BIGINT,
  sw_popular_country             VARCHAR(100),
  sw_country_rank                BIGINT,
  market_scanned                 VARCHAR(100),
  search_engine                  VARCHAR(100),
  keyword                        VARCHAR(1024),
  page_no                        INT,
  url_rank                       INT,
  quality_of_print               VARCHAR(100),
  language_1                     VARCHAR(100),
  language_2                     VARCHAR(100),
  language_3                     VARCHAR(100),
  language_4                     VARCHAR(100),
  linking_html_tag               TEXT,
  url_status_google              VARCHAR(100),
  urls_delisting_date_google     DATETIME,
  url_status_bing                VARCHAR(100),
  urls_delisting_date_bing       DATETIME,
  url_status_yandex              VARCHAR(100),
  urls_delisting_date_yandex     DATETIME,
  notice_id_google               VARCHAR(255),
  notice_sent_date_google        DATETIME,
  notice_id_bing                 VARCHAR(255),
  notice_sent_date_bing          DATETIME,
  notice_id_yandex               VARCHAR(255),
  notice_sent_date_yandex        DATETIME,
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_linking_url      (linking_url_hash),
  INDEX idx_date_ident           (date_of_identification),
  INDEX idx_copyright_owner      (copyright_owner(100)),
  INDEX idx_market               (market_scanned),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 2. Ads Tutorials - Social Media  →  unique: video_posts_urls
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ads_tutorials_social_media (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  date_of_identification         DATETIME,
  platform_name                  VARCHAR(100),
  platform_domain                VARCHAR(255),
  title                          VARCHAR(512),
  content_owner                  VARCHAR(512),
  pirate_domain                  VARCHAR(255),
  pirate_brand                   VARCHAR(255),
  video_posts_urls               TEXT,
  video_posts_urls_hash          VARCHAR(64) AS (SHA2(video_posts_urls, 256)) STORED,
  channel_profile_page_urls      TEXT,
  channel_page_profile_name      VARCHAR(512),
  subscribers                    BIGINT,
  views                          BIGINT,
  post_description               TEXT,
  language_of_post               VARCHAR(100),
  type_of_post                   VARCHAR(100),
  linking_url                    TEXT,
  keywords                       VARCHAR(512),
  market_scanned                 VARCHAR(100),
  url_status                     VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  url_removal_date               DATETIME,
  notice_id                      VARCHAR(255),
  notice_sent_date               DATETIME,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_video_url        (video_posts_urls_hash),
  INDEX idx_date_ident           (date_of_identification),
  INDEX idx_platform             (platform_name),
  INDEX idx_content_owner        (content_owner(100)),
  INDEX idx_url_status           (url_status),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 3. Password Sharing - Social Media  →  unique: listing_posts_urls
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS password_sharing_social_media (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  date_of_identification         DATETIME,
  platform_name                  VARCHAR(100),
  platform_domain_name           VARCHAR(255),
  content_owner                  VARCHAR(512),
  ott_platform_1                 VARCHAR(255),
  ott_platform_2                 VARCHAR(255),
  ott_platform_3                 VARCHAR(255),
  ott_platform_4                 VARCHAR(255),
  listing_posts_urls             TEXT,
  listing_posts_urls_hash        VARCHAR(64) AS (SHA2(listing_posts_urls, 256)) STORED,
  channel_profile_page_urls      TEXT,
  channel_page_profile_name      VARCHAR(512),
  subscribers                    BIGINT,
  views                          BIGINT,
  post_description               TEXT,
  language_of_post               VARCHAR(100),
  type_of_post                   VARCHAR(100),
  linking_url                    TEXT,
  login_id                       VARCHAR(255),
  login_password                 VARCHAR(255),
  login_validation_status        VARCHAR(100),
  seller_name                    VARCHAR(512),
  seller_country                 VARCHAR(100),
  listing_price                  DECIMAL(12,2),
  listing_currency               VARCHAR(20),
  offers_discount                VARCHAR(255),
  keywords                       VARCHAR(512),
  market_scanned                 VARCHAR(100),
  url_status                     VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  removal_date                   DATETIME,
  notice_id                      VARCHAR(255),
  notice_sent_date               DATETIME,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_listing_url      (listing_posts_urls_hash),
  INDEX idx_date_ident           (date_of_identification),
  INDEX idx_platform             (platform_name),
  INDEX idx_content_owner        (content_owner(100)),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_seller_country       (seller_country),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 4. Password Sharing - Marketplace  →  unique: listing_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS password_sharing_marketplace (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  date_of_identification         DATETIME,
  platform_name                  VARCHAR(100),
  platform_type                  VARCHAR(100),
  platform_domain_name           VARCHAR(255),
  market_scanned                 VARCHAR(100),
  content_owner                  VARCHAR(512),
  ott_platform_1                 VARCHAR(255),
  ott_platform_2                 VARCHAR(255),
  ott_platform_3                 VARCHAR(255),
  ott_platform_4                 VARCHAR(255),
  listing_url                    TEXT,
  listing_url_hash               VARCHAR(64) AS (SHA2(listing_url, 256)) STORED,
  login_id                       VARCHAR(255),
  login_password                 VARCHAR(255),
  login_validation_status        VARCHAR(100),
  website                        VARCHAR(512),
  listing_title                  VARCHAR(512),
  seller_name                    VARCHAR(512),
  shop_url                       TEXT,
  seller_country                 VARCHAR(100),
  listing_price                  DECIMAL(12,2),
  listing_currency               VARCHAR(20),
  offers_discount                VARCHAR(255),
  validity                       VARCHAR(100),
  type_of_listing                VARCHAR(100),
  keywords                       VARCHAR(512),
  no_of_reviews                  INT,
  ratings                        DECIMAL(3,2),
  no_of_buys                     INT,
  removal_date                   DATETIME,
  removal_timestamp              DATETIME,
  removal_status                 VARCHAR(100),
  url_status                     VARCHAR(100),
  notice_id                      VARCHAR(255),
  notice_sent_date               DATETIME,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_listing_url      (listing_url_hash),
  INDEX idx_date_ident           (date_of_identification),
  INDEX idx_platform             (platform_name),
  INDEX idx_content_owner        (content_owner(100)),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_seller_country       (seller_country),
  INDEX idx_market               (market_scanned),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 5. IPTV & Apps - Internet  →  unique: source_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS iptv_apps_internet (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  identification_date            DATETIME,
  week_bise                      VARCHAR(50),
  type                           VARCHAR(100),
  intermediary_type              VARCHAR(100),
  iptv_application_name          VARCHAR(255),
  source_url                     TEXT,
  source_url_hash                VARCHAR(64) AS (SHA2(source_url, 256)) STORED,
  source_domain                  VARCHAR(512),
  keywords                       VARCHAR(512),
  search_engine                  VARCHAR(100),
  page_no                        INT,
  page_rank                      INT,
  market_country                 VARCHAR(100),
  language                       VARCHAR(100),
  trademark_wordmark             VARCHAR(255),
  content_owner                  VARCHAR(512),
  subscription_paid_free         VARCHAR(50),
  subscription_cost              VARCHAR(100),
  subscription_currency          VARCHAR(20),
  validity                       VARCHAR(100),
  sw_data_month                  VARCHAR(50),
  search_traffic                 BIGINT,
  sw_monthly_traffic             BIGINT,
  unique_monthly_visits          BIGINT,
  sw_global_rank                 BIGINT,
  sw_popular_country             VARCHAR(100),
  sw_country_rank                BIGINT,
  approved_for_enforcement       VARCHAR(10),
  disruption_status              VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  notice_sent_date_google        DATETIME,
  notice_id_google               VARCHAR(255),
  url_delisting_status_google    VARCHAR(100),
  tcrp_case_id                   VARCHAR(255),
  tat_google                     VARCHAR(100),
  notice_sent_date_bing          DATETIME,
  notice_id_bing                 VARCHAR(255),
  url_delisting_status_bing      VARCHAR(100),
  tat_bing                       VARCHAR(100),
  notice_sent_date_yandex        DATETIME,
  notice_id_yandex               VARCHAR(255),
  url_delisting_status_yandex    VARCHAR(100),
  tat_yandex                     VARCHAR(100),
  first_notice_date              DATETIME,
  notice_id                      VARCHAR(255),
  date_of_last_followup          DATE,
  no_of_times_followup           INT,
  removal_date                   DATE,
  tat                            VARCHAR(100),
  additional_remarks             TEXT,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_url       (source_url_hash),
  INDEX idx_ident_date           (identification_date),
  INDEX idx_iptv_name            (iptv_application_name),
  INDEX idx_market               (market_country),
  INDEX idx_disruption           (disruption_status),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_content_owner        (content_owner(100)),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 6. IPTV & Apps - Apps  →  unique: source_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS iptv_apps_apps (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  identification_date            DATETIME,
  week_bise                      VARCHAR(50),
  type                           VARCHAR(100),
  platform                       VARCHAR(255),
  iptv_application_name          VARCHAR(255),
  source_url                     TEXT,
  source_url_hash                VARCHAR(64) AS (SHA2(source_url, 256)) STORED,
  source_domain                  VARCHAR(512),
  platforms                      VARCHAR(255),
  keywords                       VARCHAR(512),
  apps_version                   VARCHAR(50),
  developer_name                 VARCHAR(512),
  developer_id                   VARCHAR(255),
  developer_website_email        VARCHAR(512),
  market                         VARCHAR(100),
  language                       VARCHAR(100),
  content_owner                  VARCHAR(512),
  subscription_paid_free         VARCHAR(50),
  subscription_cost              VARCHAR(100),
  subscription_currency          VARCHAR(20),
  validity                       VARCHAR(100),
  sw_data_month                  VARCHAR(50),
  search_traffic                 BIGINT,
  sw_monthly_traffic             BIGINT,
  unique_monthly_visits          BIGINT,
  sw_global_rank                 BIGINT,
  sw_popular_country             VARCHAR(100),
  sw_country_rank                BIGINT,
  approved_for_enforcement       VARCHAR(10),
  disruption_status              VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  notice_sent_date_google        DATETIME,
  notice_id_google               VARCHAR(255),
  url_delisting_status_google    VARCHAR(100),
  tcrp_case_id                   VARCHAR(255),
  notice_sent_date_bing          DATETIME,
  notice_id_bing                 VARCHAR(255),
  url_delisting_status_bing      VARCHAR(100),
  notice_sent_date_yandex        DATETIME,
  notice_id_yandex               VARCHAR(255),
  url_delisting_status_yandex    VARCHAR(100),
  first_notice_date              DATETIME,
  notice_id                      VARCHAR(255),
  date_of_last_followup          DATE,
  no_of_times_followup           INT,
  removal_date                   DATE,
  tat                            VARCHAR(100),
  remarks                        TEXT,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_url       (source_url_hash),
  INDEX idx_ident_date           (identification_date),
  INDEX idx_platform             (platform),
  INDEX idx_iptv_name            (iptv_application_name),
  INDEX idx_market               (market),
  INDEX idx_disruption           (disruption_status),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_content_owner        (content_owner(100)),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 7. IPTV & Apps - Social Media  →  unique: source_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS iptv_apps_social_media (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  identification_date            DATETIME,
  week_bise                      VARCHAR(50),
  type                           VARCHAR(100),
  iptv_application_name          VARCHAR(255),
  source_url                     TEXT,
  source_url_hash                VARCHAR(64) AS (SHA2(source_url, 256)) STORED,
  channel_profile_page_urls      TEXT,
  source_domain                  VARCHAR(512),
  infringement_type              VARCHAR(255),
  channel_page_profile_name      VARCHAR(512),
  copyright_owner                VARCHAR(512),
  subscriber_follower            BIGINT,
  views_likes                    VARCHAR(100),
  keywords                       VARCHAR(512),
  market_country                 VARCHAR(100),
  approved_for_enforcement       VARCHAR(10),
  disruption_status              VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  date_time_first_notice         DATETIME,
  notice_id                      VARCHAR(255),
  date_of_last_followup          DATE,
  no_of_times_followup           INT,
  removal_date                   DATE,
  tat                            VARCHAR(100),
  additional_remarks             TEXT,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_url       (source_url_hash),
  INDEX idx_ident_date           (identification_date),
  INDEX idx_iptv_name            (iptv_application_name),
  INDEX idx_market               (market_country),
  INDEX idx_disruption           (disruption_status),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_copyright            (copyright_owner(100)),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 8. IPTV & Apps - Marketplace  →  unique: source_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS iptv_apps_marketplace (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  identification_date            DATETIME,
  week_bise                      VARCHAR(50),
  type                           VARCHAR(100),
  iptv_application_name          VARCHAR(255),
  intermediary_type              VARCHAR(255),
  source_url                     TEXT,
  source_url_hash                VARCHAR(64) AS (SHA2(source_url, 256)) STORED,
  source_domain                  VARCHAR(512),
  platform                       VARCHAR(255),
  seller_profile_page_url        TEXT,
  copyright_owner                VARCHAR(512),
  device_name                    VARCHAR(255),
  post_title                     TEXT,
  keywords                       VARCHAR(512),
  market_country                 VARCHAR(100),
  language                       VARCHAR(100),
  likes_views                    VARCHAR(100),
  followers_subscribers          BIGINT,
  subscription_cost              DECIMAL(12,2),
  subscription_currency          VARCHAR(20),
  validity                       VARCHAR(100),
  seller_name_company            VARCHAR(512),
  seller_country                 VARCHAR(100),
  number_of_buys                 BIGINT,
  approved_for_enforcement       VARCHAR(10),
  disruption_status              VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  date_time_first_notice         DATETIME,
  notice_id                      VARCHAR(255),
  date_of_last_followup          DATE,
  no_of_times_followup           INT,
  removal_date                   DATE,
  tat                            VARCHAR(100),
  additional_remarks             TEXT,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_url       (source_url_hash),
  INDEX idx_ident_date           (identification_date),
  INDEX idx_iptv_name            (iptv_application_name),
  INDEX idx_platform             (platform),
  INDEX idx_market               (market_country),
  INDEX idx_disruption           (disruption_status),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_copyright            (copyright_owner(100)),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- 9. IPTV & Apps - Meta Ads  →  unique: source_url
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS iptv_apps_meta_ads (
  id                             CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  sr_no                          INT,
  identification_date            DATETIME,
  week_bise                      VARCHAR(50),
  type                           VARCHAR(100),
  iptv_application_name          VARCHAR(255),
  intermediary_type              VARCHAR(255),
  source_url                     TEXT,
  source_url_hash                VARCHAR(64) AS (SHA2(source_url, 256)) STORED,
  advertiser_channel_url         TEXT,
  platform                       VARCHAR(255),
  library_id                     VARCHAR(255),
  copyright_owner                VARCHAR(512),
  post_title                     TEXT,
  keywords                       VARCHAR(512),
  market_country                 VARCHAR(100),
  language                       VARCHAR(100),
  followers_subscribers          BIGINT,
  listing_date                   DATE,
  seller_name                    VARCHAR(512),
  approved_for_enforcement       VARCHAR(10),
  disruption_status              VARCHAR(100),
  removal_status                 VARCHAR(100),
  removal_timestamp              DATETIME,
  date_time_first_notice         DATETIME,
  notice_id                      VARCHAR(255),
  date_of_last_followup          DATE,
  no_of_times_followup           INT,
  removal_date                   DATE,
  tat                            VARCHAR(100),
  remarks                        TEXT,
  uploaded_by                    CHAR(36),
  upload_batch_id                VARCHAR(64),
  created_at                     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_url       (source_url_hash),
  INDEX idx_ident_date           (identification_date),
  INDEX idx_iptv_name            (iptv_application_name),
  INDEX idx_platform             (platform),
  INDEX idx_market               (market_country),
  INDEX idx_disruption           (disruption_status),
  INDEX idx_removal_status       (removal_status),
  INDEX idx_copyright            (copyright_owner(100)),
  INDEX idx_uploaded_by          (uploaded_by),
  INDEX idx_batch                (upload_batch_id),
  INDEX idx_created              (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ────────────────────────────────────────────────────────────
-- API Tokens  (used by /api/v1/* public endpoints)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS api_tokens (
  id           CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  token        VARCHAR(64)  NOT NULL UNIQUE,
  user_id      CHAR(36)     NOT NULL,
  user_name    VARCHAR(100) NOT NULL,
  description  VARCHAR(255),
  expires_at   DATETIME,
  last_used_at DATETIME,
  is_active    TINYINT(1) NOT NULL DEFAULT 1,
  created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_token  (token),
  INDEX idx_user   (user_id),
  INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS api_token_usage (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  token_id    CHAR(36)     NOT NULL,
  endpoint    VARCHAR(255),
  params      TEXT,
  ip_address  VARCHAR(45),
  status_code SMALLINT,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_token_id (token_id),
  INDEX idx_created  (created_at),
  FOREIGN KEY (token_id) REFERENCES api_tokens(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
