// Sheet configuration - defines every module's table, columns, and unique URL field
export const SHEET_CONFIG = {
  'Unauthorized Search Result': {
    table: 'unauthorized_search_result',
    label: 'Unauthorized Search Result',
    icon: 'fa-magnifying-glass',
    color: 'red',
    uniqueUrlCol: 'linking_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification',      label: 'Date of Identification',    excel: 'Date of Identification',    type: 'datetime' },
      { key: 'title',                        label: 'Title',                     excel: 'Title' },
      { key: 'copyright_owner',              label: 'Copyright Owner',           excel: 'Copyright Owner' },
      { key: 'linking_url',                  label: 'Linking URL',               excel: 'Linking URL',               type: 'url' },
      { key: 'website',                      label: 'Website',                   excel: 'Website' },
      { key: 'pirate_website_brand',         label: 'Pirate Website Brand',      excel: 'Pirate Website Brand' },
      { key: 'sw_data_month',                label: 'SW Data Month',             excel: 'SW Data Month' },
      { key: 'sw_monthly_traffic',           label: 'SW Monthly Traffic',        excel: 'SW Monthly Traffic',        type: 'number' },
      { key: 'traffic_from_search_engines',  label: 'SW Search Traffic',         excel: 'SW Search Traffic',         type: 'number' },
      { key: 'sw_global_rank',               label: 'SW Global Rank',            excel: 'SW Global Rank',            type: 'number' },
      { key: 'sw_popular_country',           label: 'SW Popular Country',        excel: 'SW Popular Country' },
      { key: 'sw_country_rank',              label: 'SW Country Rank',           excel: 'SW Country Rank',           type: 'number' },
      { key: 'market_scanned',               label: 'Market Scanned',            excel: 'Market Scanned' },
      { key: 'search_engine',                label: 'Search Engine',             excel: 'Search Engine' },
      { key: 'keyword',                      label: 'Keyword',                   excel: 'Keyword' },
      { key: 'page_no',                      label: 'Page No',                   excel: 'Page No',                   type: 'number' },
      { key: 'url_rank',                     label: 'URL Rank',                  excel: 'URL Rank',                  type: 'number' },
      { key: 'quality_of_print',             label: 'Quality of Print',          excel: 'Quality of Print' },
      { key: 'language_1',                   label: 'Language 1',                excel: 'Language 1' },
      { key: 'language_2',                   label: 'Language 2',                excel: 'Language 2' },
      { key: 'language_3',                   label: 'Language 3',                excel: 'Language 3' },
      { key: 'language_4',                   label: 'Language 4',                excel: 'Language 4' },
      { key: 'linking_html_tag',             label: 'Linking Html Tag',          excel: 'Linking Html Tag' },
      { key: 'notice_id_google',             label: 'Notice ID Google',          excel: 'Notice ID Google' },
      { key: 'notice_sent_date_google',      label: 'Notice Sent Date Google',   excel: 'Notice Sent Date Google',   type: 'datetime' },
      { key: 'urls_delisting_date_google',   label: 'URLs Delisting Date Google', excel: 'URLs Delisting Date Google', type: 'datetime' },
      { key: 'url_status_google',            label: 'URL Status Google',         excel: 'URL Status Google',         type: 'status' },
      { key: 'notice_id_bing',               label: 'Notice ID Bing',            excel: 'Notice ID Bing' },
      { key: 'notice_sent_date_bing',        label: 'Notice Sent Date Bing',     excel: 'Notice Sent Date Bing',     type: 'datetime' },
      { key: 'urls_delisting_date_bing',     label: 'URLs Delisting Date Bing',  excel: 'URLs Delisting Date Bing',  type: 'datetime' },
      { key: 'url_status_bing',              label: 'URL Status Bing',           excel: 'URL Status Bing',           type: 'status' },
      { key: 'notice_id_yandex',             label: 'Notice ID Yandex',          excel: 'Notice ID Yandex' },
      { key: 'notice_sent_date_yandex',      label: 'Notice Sent Date Yandex',   excel: 'Notice Sent Date Yandex',   type: 'datetime' },
      { key: 'urls_delisting_date_yandex',   label: 'URLs Delisting Date Yandex', excel: 'URLs Delisting Date Yandex', type: 'datetime' },
      { key: 'url_status_yandex',            label: 'URL Status Yandex',         excel: 'URL Status Yandex',         type: 'status' },
      { key: 'tat_google',                   label: 'Google TAT',                excel: 'Google TAT' },
    ]
  },

  'Ads Tutorials- Social Media': {
    table: 'ads_tutorials_social_media',
    label: 'Ads Tutorials - Social Media',
    icon: 'fa-bullhorn',
    color: 'blue',
    uniqueUrlCol: 'video_posts_urls',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification',   label: 'Date of Identification',  excel: 'Date of Identification',  type: 'datetime' },
      { key: 'platform_name',            label: 'Platform Name',           excel: 'Platform Name' },
      { key: 'platform_domain',          label: 'Platform Domain',         excel: 'Platform Domain' },
      { key: 'content_owner',            label: 'Content Owner',           excel: 'Content Owner' },
      { key: 'pirate_domain',            label: 'Pirate Domain',           excel: 'Pirate Domain' },
      { key: 'pirate_brand',             label: 'Pirate Brand',            excel: 'Pirate Brand' },
      { key: 'video_posts_urls',         label: 'Video Posts URL',         excel: 'Video Posts URL',         type: 'url' },
      { key: 'channel_profile_page_urls', label: 'Channel/Profile/Page URL', excel: 'Channel/Profile/Page URL', type: 'url' },
      { key: 'channel_page_profile_name', label: 'Channel/Profile/Page Name', excel: 'Channel/Profile/Page Name' },
      { key: 'subscribers',              label: 'Subscribers',             excel: 'Subscribers',             type: 'number' },
      { key: 'views',                    label: 'Views',                   excel: 'Views',                   type: 'number' },
      { key: 'post_description',         label: 'Post Description',        excel: 'Post Description' },
      { key: 'language_of_post',         label: 'Language of Post',        excel: 'Language of Post' },
      { key: 'type_of_post',             label: 'Type of Post',            excel: 'Type of Post' },
      { key: 'linking_url',              label: 'Linking URL',             excel: 'Linking URL',             type: 'url' },
      { key: 'keywords',                 label: 'Keywords',                excel: 'Keywords' },
      { key: 'market_scanned',           label: 'Market Scanned',          excel: 'Market Scanned' },
      { key: 'url_status',               label: 'URL Status',              excel: 'URL Status',              type: 'status' },
      { key: 'notice_id',                label: 'Notice ID',               excel: 'Notice ID' },
      { key: 'notice_sent_date',         label: 'Notice Sent Date',        excel: 'Notice Sent Date',        type: 'datetime' },
      { key: 'url_removal_date',         label: 'URL Removal Date',        excel: 'URL Removal Date',        type: 'datetime' },
      { key: 'tat',                      label: 'TAT',                     excel: 'TAT' },
    ]
  },

  'Password Sharing-Social Med.': {
    table: 'password_sharing_social_media',
    label: 'Password Sharing - Social Media',
    icon: 'fa-lock',
    color: 'orange',
    uniqueUrlCol: 'listing_posts_urls',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification',   label: 'Date of Identification',  excel: 'Date of Identification',  type: 'datetime' },
      { key: 'platform_name',            label: 'Platform Name',           excel: 'Platform Name' },
      { key: 'platform_domain_name',     label: 'Platform Domain Name',    excel: 'Platform Domain Name' },
      { key: 'content_owner',            label: 'Content Owner',           excel: 'Content Owner' },
      { key: 'listing_posts_urls',       label: 'Listing URL',             excel: 'Listing URL',             type: 'url' },
      { key: 'channel_profile_page_urls', label: 'Channel/Profile/Page URL', excel: 'Channel/Profile/Page URL', type: 'url' },
      { key: 'channel_page_profile_name', label: 'Channel/Page/Profile Name', excel: 'Channel/Page/Profile Name' },
      { key: 'subscribers',              label: 'Subscribers',             excel: 'Subscribers',             type: 'number' },
      { key: 'views',                    label: 'Views',                   excel: 'Views',                   type: 'number' },
      { key: 'post_description',         label: 'Post Description',        excel: 'Post Description' },
      { key: 'language_of_post',         label: 'Language of Post',        excel: 'Language of Post' },
      { key: 'type_of_post',             label: 'Type of Post',            excel: 'Type of Post' },
      { key: 'linking_url',              label: 'Linking URL',             excel: 'Linking URL',             type: 'url' },
      { key: 'credentials_available',    label: 'Credentials Available',   excel: 'Credentials Available' },
      { key: 'login_id',                 label: 'Login ID',                excel: 'Login ID' },
      { key: 'login_password',           label: 'Login Password',          excel: 'Login Password' },
      { key: 'login_validation_status',  label: 'Login Validation Status', excel: 'Login Validation Status', type: 'status' },
      { key: 'seller_name',              label: 'Seller Name',             excel: 'Seller Name' },
      { key: 'seller_country',           label: 'Seller Country',          excel: 'Seller Country' },
      { key: 'listing_price',            label: 'Listing Price',           excel: 'Listing Price',           type: 'number' },
      { key: 'listing_currency',         label: 'Listing Currency',        excel: 'Listing Currency' },
      { key: 'offers_discount',          label: 'Offers/Discount',         excel: 'Offers/Discount' },
      { key: 'keywords',                 label: 'Keywords',                excel: 'Keywords' },
      { key: 'market_scanned',           label: 'Market Scanned',          excel: 'Market Scanned' },
      { key: 'notes',                    label: 'Notes',                   excel: 'Notes' },
      { key: 'url_status',               label: 'URL Status',              excel: 'URL Status',              type: 'status' },
      { key: 'notice_id',                label: 'Notice ID',               excel: 'Notice ID' },
      { key: 'notice_sent_date',         label: 'Notice Sent Date',        excel: 'Notice Sent Date',        type: 'datetime' },
      { key: 'removal_date',             label: 'URL Removal Date',        excel: 'URL Removal Date',        type: 'datetime' },
      { key: 'tat',                      label: 'TAT',                     excel: 'TAT' },
    ]
  },

  'Password Sharing-Marketplace': {
    table: 'password_sharing_marketplace',
    label: 'Password Sharing - Marketplace',
    icon: 'fa-cart-shopping',
    color: 'purple',
    uniqueUrlCol: 'listing_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification',  label: 'Date of Identification',  excel: 'Date of Identification',  type: 'datetime' },
      { key: 'platform_name',           label: 'Platform Name',           excel: 'Platform Name' },
      { key: 'platform_domain_name',    label: 'Platform Domain Name',    excel: 'Platform Domain Name' },
      { key: 'market_scanned',          label: 'Market Scanned',          excel: 'Market Scanned' },
      { key: 'content_owner',           label: 'Content Owner',           excel: 'Content Owner' },
      { key: 'listing_url',             label: 'Listing URL',             excel: 'Listing URL',             type: 'url' },
      { key: 'login_id',                label: 'Login ID',                excel: 'Login ID' },
      { key: 'login_password',          label: 'Login Password',          excel: 'Login Password' },
      { key: 'login_validation_status', label: 'Login Validation Status', excel: 'Login Validation Status', type: 'status' },
      { key: 'listing_title',           label: 'Listing Title',           excel: 'Listing Title' },
      { key: 'seller_name',             label: 'Seller Name',             excel: 'Seller Name' },
      { key: 'shop_url',                label: 'Seller URL',              excel: 'Seller URL',              type: 'url' },
      { key: 'seller_country',          label: 'Seller Country',          excel: 'Seller Country' },
      { key: 'listing_price',           label: 'Listing Price',           excel: 'Listing Price',           type: 'number' },
      { key: 'listing_currency',        label: 'Listing Currency',        excel: 'Listing Currency' },
      { key: 'offers_discount',         label: 'Offers Discount',         excel: 'Offers Discount' },
      { key: 'validity',                label: 'Validity',                excel: 'Validity' },
      { key: 'type_of_listing',         label: 'Type Of Listing',         excel: 'Type Of Listing' },
      { key: 'keywords',                label: 'Keywords',                excel: 'Keywords' },
      { key: 'no_of_reviews',           label: 'No Of Reviews',           excel: 'No Of Reviews',           type: 'number' },
      { key: 'ratings',                 label: 'Ratings',                 excel: 'Ratings',                 type: 'number' },
      { key: 'no_of_buys',              label: 'No. of Buys',             excel: 'No. of Buys',             type: 'number' },
      { key: 'notes',                   label: 'Notes',                   excel: 'Notes' },
      { key: 'url_status',              label: 'URL Status',              excel: 'URL Status',              type: 'status' },
      { key: 'notice_id',               label: 'Notice ID',               excel: 'Notice ID' },
      { key: 'notice_sent_date',        label: 'Notice Sent Date',        excel: 'Notice Sent Date',        type: 'datetime' },
      { key: 'removal_date',            label: 'URL Removal Date',        excel: 'URL Removal Date',        type: 'datetime' },
      { key: 'tat',                     label: 'TAT',                     excel: 'TAT' },
    ]
  },

  'IPTV & Apps - Internet': {
    table: 'iptv_apps_internet',
    label: 'IPTV & Apps - Internet',
    icon: 'fa-globe',
    color: 'teal',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date',         label: 'Identification Date',              excel: 'Identification Date',                            type: 'datetime' },
      { key: 'week_bise',                    label: 'Week',                             excel: 'Week' },
      { key: 'type',                         label: 'Type',                             excel: 'Type' },
      { key: 'iptv_application_name',        label: 'IPTV/Application Name',            excel: 'IPTV/Application Name' },
      { key: 'source_url',                   label: 'Source URL',                       excel: 'Source URL',                                     type: 'url' },
      { key: 'source_domain',                label: 'Source Domains',                   excel: 'Source Domains' },
      { key: 'keywords',                     label: 'Keywords',                         excel: 'Keywords' },
      { key: 'search_engine',                label: 'Search Engine',                    excel: 'Search Engine' },
      { key: 'page_no',                      label: 'Page No.',                         excel: 'Page No.',                                       type: 'number' },
      { key: 'page_rank',                    label: 'Page Rank',                        excel: 'Page Rank',                                      type: 'number' },
      { key: 'market_country',               label: 'Market (Country)',                 excel: 'Market (Country)' },
      { key: 'content_owner',                label: 'Content Owner',                    excel: 'Content Owner' },
      { key: 'trademark_wordmark',           label: 'Trademarks Name (Sports)',         excel: 'Trademarks Name (Sports)' },
      { key: 'category',                     label: 'Category',                         excel: 'Category (Sport/Content/Sports+Content)' },
      { key: 'sw_data_month',                label: 'SW Data Month',                    excel: 'SW Data Month' },
      { key: 'search_traffic',               label: 'Search Traffic',                   excel: 'Search Traffic',                                 type: 'number' },
      { key: 'sw_monthly_traffic',           label: 'SW Monthly Traffic',               excel: 'SW Monthly Traffic',                             type: 'number' },
      { key: 'unique_monthly_visits',        label: 'Unique Monthly Visits',            excel: 'Unique Monthly Visits',                          type: 'number' },
      { key: 'sw_global_rank',               label: 'SW Global Rank',                   excel: 'SW Global Rank',                                 type: 'number' },
      { key: 'sw_popular_country',           label: 'SW Popular Country',               excel: 'SW Popular Country' },
      { key: 'sw_country_rank',              label: 'SW Country Rank',                  excel: 'SW Country Rank',                                type: 'number' },
      { key: 'approved_for_enforcement',     label: 'Approved for Enforcement (Y/N)',   excel: 'Approved for Enforcement (Y/N)' },
      { key: 'disruption_status',            label: 'Website Disruption Status',        excel: 'Website Disruption Status (Active/Suspended)',   type: 'status' },
      { key: 'url_delisting_status_google',  label: 'URLs Delisting Status',            excel: 'URLs Delisting Status (Approved/Pending/Denied)', type: 'status' },
      { key: 'notice_sent_date_google',      label: 'Notice Sent Date & Time (Google)', excel: 'Notice Sent Date & Time (Google)',               type: 'datetime' },
      { key: 'notice_id_google',             label: 'Notice ID # Google',               excel: 'Notice ID # Google' },
      { key: 'tcrp_case_id',                 label: 'TCRP CASE ID',                     excel: 'TCRP CASE ID' },
      { key: 'delisting_timestamp_google',   label: 'Delisting Timestamp (Google)',     excel: 'Delisting Timestamp (Google)',                   type: 'datetime' },
      { key: 'tat_google',                   label: 'TAT (Google)',                     excel: 'TAT (Google)' },
      { key: 'url_delisting_status_bing',    label: 'URLs Delisting Status Bing',       excel: 'URLs Delisting Status Bing (Approved/Pending/Rejected)', type: 'status' },
      { key: 'notice_sent_date_bing',        label: 'Notice Sent Date & Time (Bing)',   excel: 'Notice Sent Date & Time (Bing)',                 type: 'datetime' },
      { key: 'notice_id_bing',               label: 'Notice ID # Bing',                 excel: 'Notice ID # Bing' },
      { key: 'tcrp_case_id_bing',            label: 'TCRP CASE ID (Bing)',              excel: 'TCRP CASE ID (Bing)' },
      { key: 'delisting_timestamp_bing',     label: 'Delisting Timestamp (Bing)',       excel: 'Delisting Timestamp (Bing)',                     type: 'datetime' },
      { key: 'tat_bing',                     label: 'TAT (Bing)',                       excel: 'TAT (Bing)' },
      { key: 'url_delisting_status_yandex',  label: 'URLs Delisting Status Yandex',     excel: 'URLs Delisting Status Yandex (Approved/Pending)', type: 'status' },
      { key: 'notice_sent_date_yandex',      label: 'Notice Sent Date & Time (Yandex)', excel: 'Notice Sent Date & Time (Yandex)',               type: 'datetime' },
      { key: 'notice_id_yandex',             label: 'Notice ID # Yandex',               excel: 'Notice ID # Yandex' },
      { key: 'tcrp_case_id_yandex',          label: 'TCRP CASE ID (Yandex)',            excel: 'TCRP CASE ID (Yandex)' },
      { key: 'delisting_timestamp_yandex',   label: 'Delisting Timestamp (Yandex)',     excel: 'Delisting Timestamp (Yandex)',                   type: 'datetime' },
      { key: 'tat_yandex',                   label: 'TAT (Yandex)',                     excel: 'TAT (Yandex)' },
    ]
  },

  'IPTV & Apps - Apps': {
    table: 'iptv_apps_apps',
    label: 'IPTV & Apps - Apps',
    icon: 'fa-mobile-screen',
    color: 'green',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date',      label: 'Identification Date',                                    excel: 'Identification Date',                                    type: 'datetime' },
      { key: 'week_bise',                label: 'Week',                                                   excel: 'Week' },
      { key: 'type',                     label: 'Type',                                                   excel: 'Type' },
      { key: 'platform',                 label: 'Platform',                                               excel: 'Platform' },
      { key: 'iptv_application_name',    label: 'IPTV/Application Name',                                  excel: 'IPTV/Application Name' },
      { key: 'source_url',               label: 'Source URL',                                             excel: 'Source URL',                                             type: 'url' },
      { key: 'source_domain',            label: 'Source Domain',                                          excel: 'Source Domain' },
      { key: 'platforms',                label: 'Platfrom',                                               excel: 'Platfrom' },
      { key: 'keywords',                 label: 'Keywords',                                               excel: 'Keywords' },
      { key: 'apps_version',             label: 'Apps Version',                                           excel: 'Apps Version' },
      { key: 'developer_name',           label: 'Developer Name',                                         excel: 'Developer Name' },
      { key: 'developer_id',             label: 'DevInfo',                                                excel: 'DevInfo' },
      { key: 'developer_website_email',  label: 'DevEmailId',                                             excel: 'DevEmailId' },
      { key: 'market',                   label: 'Market',                                                 excel: 'Market' },
      { key: 'content_owner',            label: 'Content Owner',                                          excel: 'Content Owner' },
      { key: 'trademark_wordmark',       label: 'Trademarks Name (Sports)',                               excel: 'Trademarks Name (Sports)' },
      { key: 'category',                 label: 'Category',                                               excel: 'Category (Sport/Content/Sports+Content)' },
      { key: 'subscription_paid_free',   label: 'Subscription Paid/Free',                                 excel: 'Subscription Paid/Free' },
      { key: 'subscription_cost',        label: 'Subscription Cost',                                      excel: 'Subscription Cost' },
      { key: 'subscription_currency',    label: 'Subscription Currency',                                  excel: 'Subscription Currency' },
      { key: 'validity',                 label: 'Validity',                                               excel: 'Validity' },
      { key: 'approved_for_enforcement', label: 'Approved for Enforcement (Y/N)',                         excel: 'Approved for Enforcement (Y/N)' },
      { key: 'disruption_status',        label: 'Disruption Status (Active/Removed)',                     excel: 'Disruption Status (Active/Removed)',                     type: 'status' },
      { key: 'first_notice_date',        label: 'First Notice Date & Time of Pirated URL Identification', excel: 'First Notice Date & Time of Pirated URL Identification', type: 'datetime' },
      { key: 'notice_id',                label: 'Notice ID',                                              excel: 'Notice ID' },
      { key: 'date_of_last_followup',    label: 'Date of Last Follow Up',                                 excel: 'Date of Last Follow Up',                                 type: 'date' },
      { key: 'no_of_times_followup',     label: 'No. of Times Follow-up',                                 excel: 'No. of Times Follow-up',                                 type: 'number' },
      { key: 'removal_timestamp',        label: 'Removal TimeStamp',                                      excel: 'Removal TimeStamp',                                      type: 'datetime' },
      { key: 'tat',                      label: 'TAT',                                                    excel: 'TAT' },
    ]
  },

  'IPTV & Apps - Social Media': {
    table: 'iptv_apps_social_media',
    label: 'IPTV & Apps - Social Media',
    icon: 'fa-share-nodes',
    color: 'pink',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date',      label: 'Identification Date',            excel: 'Identification Date',            type: 'datetime' },
      { key: 'week_bise',                label: 'Week',                           excel: 'Week' },
      { key: 'type',                     label: 'Type',                           excel: 'Type' },
      { key: 'iptv_application_name',    label: 'IPTV/Application Name',          excel: 'IPTV/Application Name' },
      { key: 'source_url',               label: 'Source URL',                     excel: 'Source URL',                     type: 'url' },
      { key: 'channel_profile_page_urls', label: 'Channel/Profile/Page URLs',     excel: 'Channel/Profile/Page URLs',      type: 'url' },
      { key: 'source_domain',            label: 'Source Domain',                  excel: 'Source Domain' },
      { key: 'infringement_type',        label: 'Infringement Type',              excel: 'Infringment Type' },
      { key: 'channel_page_profile_name', label: 'Channel/Page/Profile Name',     excel: 'Channel/Page/Profile Name' },
      { key: 'copyright_owner',          label: 'Copyright Owner',                excel: 'Copyright Owner' },
      { key: 'trademark_wordmark',       label: 'Trademarks Name (Sports)',       excel: 'Trademarks Name (Sports)' },
      { key: 'category',                 label: 'Category',                       excel: 'Category (Sport/Content/Sports+Content)' },
      { key: 'subscriber_follower',      label: 'Subscriber/Follower',            excel: 'Subscriber/Follower',            type: 'number' },
      { key: 'views_likes',              label: 'Views/Likes if Applicable',      excel: 'Views/Likes if Applicable' },
      { key: 'keywords',                 label: 'Keywords',                       excel: 'Keywords' },
      { key: 'market_country',           label: 'Market (Country)',               excel: 'Market (Country)' },
      { key: 'approved_for_enforcement', label: 'Approved for Enforcement (Y/N)', excel: 'Approved for Enforcement (Y/N)' },
      { key: 'disruption_status',        label: 'Disruption Status (Active/Removed)', excel: 'Disruption Status (Active/Removed)', type: 'status' },
      { key: 'date_time_first_notice',   label: 'Date & Time of First Notice',    excel: 'Date & Time of First Notice',    type: 'datetime' },
      { key: 'notice_id',                label: 'Notice ID #',                    excel: 'Notice ID #' },
      { key: 'date_of_last_followup',    label: 'Date of Last Follow Up',         excel: 'Date of Last Follow Up',         type: 'date' },
      { key: 'no_of_times_followup',     label: 'No. of Times Follow-up',         excel: 'No. of Times Follow-up',         type: 'number' },
      { key: 'removal_timestamp',        label: 'Removal TimeStamp',              excel: 'Removal TimeStamp',              type: 'datetime' },
      { key: 'tat',                      label: 'TAT',                            excel: 'TAT' },
    ]
  },

  'IPTV & Apps - Marketplace': {
    table: 'iptv_apps_marketplace',
    label: 'IPTV & Apps - Marketplace',
    icon: 'fa-store',
    color: 'yellow',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date',      label: 'Identification Date',            excel: 'Identification Date',            type: 'datetime' },
      { key: 'week_bise',                label: 'Week',                           excel: 'Week' },
      { key: 'type',                     label: 'Type',                           excel: 'Type' },
      { key: 'iptv_application_name',    label: 'IPTV/Application Name',          excel: 'IPTV/Application Name' },
      { key: 'intermediary_type',        label: 'Intermediary Type',              excel: 'Intermediary Type' },
      { key: 'source_url',               label: 'Source URL',                     excel: 'Source URL',                     type: 'url' },
      { key: 'source_domain',            label: 'Source Domain',                  excel: 'Source Domain' },
      { key: 'platform',                 label: 'Platform',                       excel: 'Platform' },
      { key: 'seller_profile_page_url',  label: 'Seller Profile/Page URL',        excel: 'Seller Profile/Page URL',        type: 'url' },
      { key: 'copyright_owner',          label: 'Copyright Owner',                excel: 'Copyright Owner' },
      { key: 'trademark_wordmark',       label: 'Trademarks Name (Sports)',       excel: 'Trademarks Name (Sports)' },
      { key: 'category',                 label: 'Category',                       excel: 'Category (Sport/Content/Sports+Content)' },
      { key: 'device_name',              label: 'Device Name',                    excel: 'Device Name' },
      { key: 'keywords',                 label: 'Keywords',                       excel: 'Keywords' },
      { key: 'market_country',           label: 'Market (Country)',               excel: 'Market (Country)' },
      { key: 'subscription_cost',        label: 'Subscription Cost',              excel: 'Subscription Cost',              type: 'number' },
      { key: 'subscription_currency',    label: 'Subscription Currency',          excel: 'Subscription Currency' },
      { key: 'seller_name_company',      label: 'Seller Name/Company',            excel: 'Seller Name/Company' },
      { key: 'seller_country',           label: 'Seller Country',                 excel: 'Seller Country' },
      { key: 'number_of_buys',           label: 'Number of buys/install/download', excel: 'Number of buys/install/download', type: 'number' },
      { key: 'approved_for_enforcement', label: 'Approved for Enforcement (Y/N)', excel: 'Approved for Enforcement (Y/N)' },
      { key: 'disruption_status',        label: 'Disruption Status (Active/Removed)', excel: 'Disruption Status (Active/Removed)', type: 'status' },
      { key: 'date_time_first_notice',   label: 'Date & Time of First Notice',    excel: 'Date & Time of First Notice',    type: 'datetime' },
      { key: 'notice_id',                label: 'Notice ID #',                    excel: 'Notice ID #' },
      { key: 'date_of_last_followup',    label: 'Date of Last Follow Up',         excel: 'Date of Last Follow Up',         type: 'date' },
      { key: 'no_of_times_followup',     label: 'No. of Times Follow-up',         excel: 'No. of Times Follow-up',         type: 'number' },
      { key: 'removal_timestamp',        label: 'Removal TimeStamp',              excel: 'Removal TimeStamp',              type: 'datetime' },
      { key: 'tat',                      label: 'TAT',                            excel: 'TAT' },
    ]
  },

  'Marketplace': {
    table: 'marketplace',
    label: 'Marketplace',
    icon: 'fa-store',
    color: 'orange',
    uniqueUrlCol: 'marketplace_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_timestamp', label: 'Date Identified', type: 'date' },
      { key: 'platform', label: 'Platform' },
      { key: 'marketplace_url', label: 'Marketplace URL', type: 'url' },
      { key: 'iptv_brands', label: 'IPTV Brands' },
      { key: 'search_term_used', label: 'Search Term' },
      { key: 'country', label: 'Country' },
      { key: 'price', label: 'Price' },
      { key: 'seller_name', label: 'Seller Name' },
      { key: 'seller_profile', label: 'Seller Profile', type: 'url' },
      { key: 'seller_status', label: 'Seller Status' },
      { key: 'language', label: 'Language' },
      { key: 'screenshot_url', label: 'Screenshot', type: 'url' },
      { key: 'enforcement_timestamp', label: 'Enforcement Date' },
      { key: 'removal_status', label: 'Removal Status', type: 'status' },
      { key: 'removal_timestamp', label: 'Removal Date' },
      { key: 'tat', label: 'TAT' },
      { key: 'category', label: 'Category' },
    ]
  },

  'Social Media': {
    table: 'social_media',
    label: 'Social Media',
    icon: 'fa-share-nodes',
    color: 'blue',
    uniqueUrlCol: 'listing_link',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_timestamp', label: 'Date Identified', type: 'datetime' },
      { key: 'platform', label: 'Platform' },
      { key: 'listing_link', label: 'Listing URL', type: 'url' },
      { key: 'iptv_brands', label: 'IPTV Brands' },
      { key: 'iptv_brand_name', label: 'IPTV Brand Name' },
      { key: 'search_term_used', label: 'Search Term' },
      { key: 'country', label: 'Country' },
      { key: 'profile_name', label: 'Profile Name' },
      { key: 'profile_url', label: 'Profile URL', type: 'url' },
      { key: 'subscriber_count', label: 'Subscribers' },
      { key: 'views', label: 'Views' },
      { key: 'language', label: 'Language' },
      { key: 'platform_division', label: 'Platform Division' },
      { key: 'screenshot_url', label: 'Screenshot', type: 'url' },
      { key: 'enforcement_timestamp', label: 'Enforcement Date' },
      { key: 'removal_status', label: 'Removal Status', type: 'status' },
      { key: 'removal_timestamp', label: 'Removal Date' },
      { key: 'tat', label: 'TAT' },
      { key: 'category', label: 'Category' },
      { key: 'profile_channel_status', label: 'Channel Status' },
      { key: 'whatsapp_number', label: 'WhatsApp' },
    ]
  },

  'IPTV & Apps - Meta Ads': {
    table: 'iptv_apps_meta_ads',
    label: 'IPTV & Apps - Meta Ads',
    icon: 'fa-tv',
    color: 'indigo',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date',       label: 'Identification Date',            excel: 'Identification Date',            type: 'datetime' },
      { key: 'week_bise',                 label: 'Week',                           excel: 'Week' },
      { key: 'type',                      label: 'Type',                           excel: 'Type' },
      { key: 'iptv_application_name',     label: 'IPTV/Application Name',          excel: 'IPTV/Application Name' },
      { key: 'intermediary_type',         label: 'Intermediary Type',              excel: 'Intermediary Type' },
      { key: 'source_url',                label: 'Source URL',                     excel: 'Source URL',                     type: 'url' },
      { key: 'advertiser_channel_url',    label: 'Advertiser Channel/Profile/Page URL', excel: 'Advertiser Channel/Profile/Page URL', type: 'url' },
      { key: 'platform',                  label: 'Platform',                       excel: 'Platform' },
      { key: 'library_id',                label: 'Library ID',                     excel: 'Library ID' },
      { key: 'copyright_owner',           label: 'Copyright Owner',                excel: 'Copyright Owner' },
      { key: 'trademark_wordmark',        label: 'Trademarks Name (Sports)',       excel: 'Trademarks Name (Sports)' },
      { key: 'category',                  label: 'Category',                       excel: 'Category (Sport/Content/Sports+Content)' },
      { key: 'keywords',                  label: 'Keywords',                       excel: 'Keywords' },
      { key: 'market_country',            label: 'Market (Country)',               excel: 'Market (Country)' },
      { key: 'followers_subscribers',     label: 'Followers/ Subscribers',         excel: 'Followers/ Subscribers',         type: 'number' },
      { key: 'listing_date',              label: 'Listing Date',                   excel: 'Listing Date',                   type: 'date' },
      { key: 'seller_name',               label: 'Seller Name',                    excel: 'Seller Name' },
      { key: 'approved_for_enforcement',  label: 'Approved for Enforcement (Y/N)', excel: 'Approved for Enforcement (Y/N)' },
      { key: 'disruption_status',         label: 'Disruption Status',              excel: 'Disruption Status',              type: 'status' },
      { key: 'date_time_first_notice',    label: 'Date & Time of First Notice',    excel: 'Date & Time of First Notice',    type: 'datetime' },
      { key: 'notice_id',                 label: 'Notice ID #',                    excel: 'Notice ID #' },
      { key: 'date_of_last_followup',     label: 'Date of Last Follow Up',         excel: 'Date of Last Follow Up',         type: 'date' },
      { key: 'no_of_times_followup',      label: 'No. of Times Follow-up',         excel: 'No. of Times Follow-up',         type: 'number' },
      { key: 'removal_timestamp',         label: 'Removal TimeStamp',              excel: 'Removal TimeStamp',              type: 'datetime' },
      { key: 'tat',                       label: 'TAT',                            excel: 'TAT' },
    ]
  },
}

export const SHEET_NAMES = Object.keys(SHEET_CONFIG)

export const SHEET_NAV = [
  { key: 'Social Media',  label: 'Social Media',  icon: 'fa-share-nodes', color: 'blue'   },
  { key: 'Marketplace',   label: 'Marketplace',   icon: 'fa-store',       color: 'orange' },
  { key: 'Unauthorized Search Result',   label: 'Unauthorized Search',       icon: 'fa-magnifying-glass', color: 'red' },
  { key: 'Ads Tutorials- Social Media',  label: 'Ads Tutorials',             icon: 'fa-bullhorn',         color: 'blue' },
  { key: 'Password Sharing-Social Med.', label: 'PW Sharing - Social',       icon: 'fa-lock',             color: 'orange' },
  { key: 'Password Sharing-Marketplace', label: 'PW Sharing - Marketplace',  icon: 'fa-cart-shopping',    color: 'purple' },
  { key: 'IPTV & Apps - Internet',       label: 'IPTV Internet',             icon: 'fa-globe',            color: 'teal' },
  { key: 'IPTV & Apps - Apps',           label: 'IPTV Apps',                 icon: 'fa-mobile-screen',    color: 'green' },
  { key: 'IPTV & Apps - Social Media',   label: 'IPTV Social Media',         icon: 'fa-share-nodes',      color: 'pink' },
  { key: 'IPTV & Apps - Marketplace',    label: 'IPTV Marketplace',          icon: 'fa-store',            color: 'yellow' },
  { key: 'IPTV & Apps - Meta Ads',       label: 'IPTV Meta Ads',             icon: 'fa-tv',               color: 'indigo' },
]

export const REMOVAL_STATUSES = [
  'Removed', 'Pending', 'Enforced', 'Not Removed',
  'Under Review', 'Appealed', 'Re-uploaded', 'Partial Removal',
  'Down', 'Up', 'Active', 'Suspended', 'Approved', 'Rejected',
]

export function getStatusBadgeClass(status) {
  if (!status) return 'badge-gray'
  const s = status.toLowerCase()
  if (s.includes('remov') || s.includes('down') || s.includes('susp') || s.includes('approv')) return 'badge-green'
  if (s.includes('pending') || s.includes('up') || s.includes('activ') || s.includes('review')) return 'badge-amber'
  if (s.includes('enforc')) return 'badge-blue'
  if (s.includes('re-upload') || s.includes('reject')) return 'badge-red'
  return 'badge-gray'
}
