// Sheet configuration - defines every module's table, columns, and unique URL field
export const SHEET_CONFIG = {
  'Unauthorized Search Result': {
    table: 'unauthorized_search_result',
    label: 'Unauthorized Search Result',
    icon: 'fa-magnifying-glass',
    color: 'red',
    uniqueUrlCol: 'linking_url',       // enforced UNIQUE in DB via hash column
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification', label: 'Date Identified', excel: 'Date of Identification', type: 'datetime' },
      { key: 'title', label: 'Title', excel: 'Title' },
      { key: 'copyright_owner', label: 'Copyright Owner', excel: 'Copyright Owner' },
      { key: 'linking_url', label: 'Linking URL', excel: 'Linking URL', type: 'url' },
      { key: 'website', label: 'Website', excel: 'Website' },
      { key: 'pirate_website_brand', label: 'Pirate Brand', excel: 'Pirate Website Brand' },
      { key: 'market_scanned', label: 'Market', excel: 'Market Scanned' },
      { key: 'search_engine', label: 'Search Engine', excel: 'Search Engine' },
      { key: 'keyword', label: 'Keyword', excel: 'Keyword' },
      { key: 'url_status_google', label: 'Status Google', excel: 'URL Status Google', type: 'status' },
      { key: 'url_status_bing', label: 'Status Bing', excel: 'URL Status Bing', type: 'status' },
      { key: 'url_status_yandex', label: 'Status Yandex', excel: 'URL Status Yandex', type: 'status' },
      { key: 'notice_id_google', label: 'Notice ID Google', excel: 'Notice ID # Google' },
      { key: 'notice_id_bing', label: 'Notice ID Bing', excel: 'Notice ID # Bing' },
      { key: 'notice_id_yandex', label: 'Notice ID Yandex', excel: 'Notice ID # Yandex' },
      { key: 'removal_status', label: 'Removal Status', excel: 'Removal Status', type: 'status' },
      { key: 'sw_monthly_traffic', label: 'SW Traffic', excel: 'SW Monthly Traffic', type: 'number' },
      { key: 'sw_global_rank', label: 'SW Rank', excel: 'SW Global Rank', type: 'number' },
      { key: 'language_1', label: 'Language 1', excel: 'Language 1' },
      { key: 'quality_of_print', label: 'Quality', excel: 'Quality of Print' },
    ]
  },

  'Ads Tutorials- Social Media': {
    table: 'ads_tutorials_social_media',
    label: 'Ads Tutorials - Social Media',
    icon: 'fa-bullhorn',
    color: 'blue',
    uniqueUrlCol: 'video_posts_urls',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification', label: 'Date Identified', excel: 'Date of Identification', type: 'datetime' },
      { key: 'platform_name', label: 'Platform', excel: 'Platform Name' },
      { key: 'content_owner', label: 'Content Owner', excel: 'Content Owner' },
      { key: 'pirate_brand', label: 'Pirate Brand', excel: 'Pirate Brand' },
      { key: 'video_posts_urls', label: 'Video/Posts URLs', excel: 'Video/Posts URLs', type: 'url' },
      { key: 'channel_profile_page_urls', label: 'Channel/Profile URL', excel: 'Channel/Profile/Page URLs', type: 'url' },
      { key: 'channel_page_profile_name', label: 'Channel/Profile Name', excel: 'Channel/Page/Profile Name' },
      { key: 'subscribers', label: 'Subscribers', excel: 'Subscribers', type: 'number' },
      { key: 'views', label: 'Views', excel: 'Views', type: 'number' },
      { key: 'type_of_post', label: 'Type', excel: 'Type of Post' },
      { key: 'market_scanned', label: 'Market', excel: 'Market Scanned' },
      { key: 'url_status', label: 'URL Status', excel: 'URL Status', type: 'status' },
      { key: 'removal_status', label: 'Removal Status', excel: 'URL Status', type: 'status' },
      { key: 'url_removal_date', label: 'Removal Date', excel: 'URL Removal Date & Time', type: 'datetime' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID #' },
      { key: 'notice_sent_date', label: 'Notice Date', excel: 'Notice Sent Date & Time', type: 'datetime' },
    ]
  },

  'Password Sharing-Social Med.': {
    table: 'password_sharing_social_media',
    label: 'Password Sharing - Social Media',
    icon: 'fa-lock',
    color: 'orange',
    uniqueUrlCol: 'listing_posts_urls',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification', label: 'Date Identified', excel: 'Date of Identification', type: 'datetime' },
      { key: 'platform_name', label: 'Platform', excel: 'Platform Name' },
      { key: 'content_owner', label: 'Content Owner', excel: 'Content Owner' },
      { key: 'ott_platform_1', label: 'OTT Platform 1', excel: 'OTT Platform/Client Platform', ottIndex: 0 },
      { key: 'ott_platform_2', label: 'OTT Platform 2', excel: 'OTT Platform/Client Platform', ottIndex: 1 },
      { key: 'ott_platform_3', label: 'OTT Platform 3', excel: 'OTT Platform/Client Platform', ottIndex: 2 },
      { key: 'ott_platform_4', label: 'OTT Platform 4', excel: 'OTT Platform/Client Platform', ottIndex: 3 },
      { key: 'listing_posts_urls', label: 'Listing/Posts URLs', excel: 'Listing/Posts URLs', type: 'url' },
      { key: 'channel_page_profile_name', label: 'Channel/Profile Name', excel: 'Channel/Page/Profile Name' },
      { key: 'seller_name', label: 'Seller Name', excel: 'Seller Name' },
      { key: 'seller_country', label: 'Seller Country', excel: 'Seller Country' },
      { key: 'listing_price', label: 'Price', excel: 'Listing Price', type: 'number' },
      { key: 'listing_currency', label: 'Currency', excel: 'Listing Currency' },
      { key: 'login_validation_status', label: 'Login Valid', excel: 'Login Validation Status', type: 'status' },
      { key: 'market_scanned', label: 'Market', excel: 'Market Scanned' },
      { key: 'removal_status', label: 'Removal Status', excel: 'URL Status', type: 'status' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal date and time', type: 'datetime' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID #' },
    ]
  },

  'Password Sharing-Marketplace': {
    table: 'password_sharing_marketplace',
    label: 'Password Sharing - Marketplace',
    icon: 'fa-cart-shopping',
    color: 'purple',
    uniqueUrlCol: 'listing_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'date_of_identification', label: 'Date Identified', excel: 'Date of Identification', type: 'datetime' },
      { key: 'platform_name', label: 'Platform', excel: 'Platform Name' },
      { key: 'platform_type', label: 'Platform Type', excel: 'Platform Type' },
      { key: 'market_scanned', label: 'Market', excel: 'Market Scanned' },
      { key: 'content_owner', label: 'Content Owner', excel: 'Content Owner' },
      { key: 'ott_platform_1', label: 'OTT Platform 1', excel: 'OTT Platform/Client Platform', ottIndex: 0 },
      { key: 'ott_platform_2', label: 'OTT Platform 2', excel: 'OTT Platform/Client Platform', ottIndex: 1 },
      { key: 'ott_platform_3', label: 'OTT Platform 3', excel: 'OTT Platform/Client Platform', ottIndex: 2 },
      { key: 'ott_platform_4', label: 'OTT Platform 4', excel: 'OTT Platform/Client Platform', ottIndex: 3 },
      { key: 'listing_url', label: 'Listing URL', excel: 'Listing URL', type: 'url' },
      { key: 'listing_title', label: 'Listing Title', excel: 'Listing Title' },
      { key: 'seller_name', label: 'Seller Name', excel: 'Seller Name' },
      { key: 'seller_country', label: 'Seller Country', excel: 'Seller Country' },
      { key: 'listing_price', label: 'Price', excel: 'Listing Price', type: 'number' },
      { key: 'no_of_reviews', label: 'Reviews', excel: 'No. of Reviews', type: 'number' },
      { key: 'no_of_buys', label: 'Buys', excel: 'No. of buys', type: 'number' },
      { key: 'removal_status', label: 'Removal Status', excel: 'URL Status', type: 'status' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal date and time', type: 'datetime' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID #' },
    ]
  },

  'IPTV & Apps - Internet': {
    table: 'iptv_apps_internet',
    label: 'IPTV & Apps - Internet',
    icon: 'fa-globe',
    color: 'teal',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date', label: 'Date', excel: 'Identification Date', type: 'datetime' },
      { key: 'week_bise', label: 'Week', excel: 'Week Bise' },
      { key: 'type', label: 'Type', excel: 'Type' },
      { key: 'intermediary_type', label: 'Intermediary', excel: 'Intermediary Type' },
      { key: 'iptv_application_name', label: 'IPTV/App Name', excel: 'IPTV/Application Name' },
      { key: 'source_url', label: 'Source URL', excel: 'Source URL', type: 'url' },
      { key: 'source_domain', label: 'Domain', excel: 'Source Domain' },
      { key: 'search_engine', label: 'Search Engine', excel: 'Search Engine' },
      { key: 'market_country', label: 'Market', excel: 'Market (Country)' },
      { key: 'content_owner', label: 'Content Owner', excel: 'Content Owner' },
      { key: 'sw_monthly_traffic', label: 'SW Traffic', excel: 'SW Monthly Traffic', type: 'number' },
      { key: 'disruption_status', label: 'Disruption Status', excel: 'Disruption Status', type: 'status' },
      { key: 'removal_status', label: 'Removal Status', excel: 'Disruption Status', type: 'status' },
      { key: 'notice_id_google', label: 'Notice ID Google', excel: 'Notice ID # Google' },
      { key: 'notice_id_bing', label: 'Notice ID Bing', excel: 'Notice ID # Bing' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal Date', type: 'date' },
      { key: 'tcrp_case_id', label: 'TCRP Case ID', excel: 'TCRP Case ID' },
      { key: 'additional_remarks', label: 'Remarks', excel: 'Additional Remarks/Information' },
    ]
  },

  'IPTV & Apps - Apps': {
    table: 'iptv_apps_apps',
    label: 'IPTV & Apps - Apps',
    icon: 'fa-mobile-screen',
    color: 'green',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date', label: 'Date', excel: 'Identification Date', type: 'datetime' },
      { key: 'type', label: 'Type', excel: 'Type' },
      { key: 'platform', label: 'Platform', excel: 'Platform' },
      { key: 'iptv_application_name', label: 'App Name', excel: 'IPTV/Application Name' },
      { key: 'source_url', label: 'Source URL', excel: 'Source URL', type: 'url' },
      { key: 'apps_version', label: 'Version', excel: 'Apps Version' },
      { key: 'developer_name', label: 'Developer', excel: 'Developer Name' },
      { key: 'market', label: 'Market', excel: 'Market' },
      { key: 'content_owner', label: 'Content Owner', excel: 'Content Owner' },
      { key: 'disruption_status', label: 'Disruption Status', excel: 'Disruption Status', type: 'status' },
      { key: 'removal_status', label: 'Removal Status', excel: 'Disruption Status', type: 'status' },
      { key: 'notice_id_google', label: 'Notice ID Google', excel: 'Notice ID # Google' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal Date', type: 'date' },
      { key: 'remarks', label: 'Remarks', excel: 'Remarks' },
    ]
  },

  'IPTV & Apps - Social Media': {
    table: 'iptv_apps_social_media',
    label: 'IPTV & Apps - Social Media',
    icon: 'fa-share-nodes',
    color: 'pink',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date', label: 'Date', excel: 'Identification Date', type: 'datetime' },
      { key: 'type', label: 'Type', excel: 'Type' },
      { key: 'iptv_application_name', label: 'IPTV/App Name', excel: 'IPTV/Application Name' },
      { key: 'source_url', label: 'Source URL', excel: 'Source URL', type: 'url' },
      { key: 'channel_profile_page_urls', label: 'Channel/Profile URL', excel: 'Channel/Profile/Page URLs', type: 'url' },
      { key: 'infringement_type', label: 'Infringement Type', excel: 'Infringment Type' },
      { key: 'channel_page_profile_name', label: 'Channel Name', excel: 'Channel/Page/Profile Name' },
      { key: 'copyright_owner', label: 'Copyright Owner', excel: 'Copyright Owner' },
      { key: 'subscriber_follower', label: 'Subscribers', excel: 'Subscriber/Follower', type: 'number' },
      { key: 'market_country', label: 'Market', excel: 'Market (Country)' },
      { key: 'disruption_status', label: 'Disruption Status', excel: 'Disruption Status', type: 'status' },
      { key: 'removal_status', label: 'Removal Status', excel: 'Disruption Status', type: 'status' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID #' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal Date', type: 'date' },
      { key: 'tat', label: 'TAT', excel: 'TAT' },
      { key: 'additional_remarks', label: 'Remarks', excel: 'Additional Remarks/Information' },
    ]
  },

  'IPTV & Apps - Marketplace': {
    table: 'iptv_apps_marketplace',
    label: 'IPTV & Apps - Marketplace',
    icon: 'fa-store',
    color: 'yellow',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date', label: 'Date', excel: 'Identification Date', type: 'datetime' },
      { key: 'type', label: 'Type', excel: 'Type' },
      { key: 'iptv_application_name', label: 'IPTV/App Name', excel: 'IPTV/Application Name' },
      { key: 'source_url', label: 'Source URL', excel: 'Source URL', type: 'url' },
      { key: 'platform', label: 'Platform', excel: 'Platform' },
      { key: 'copyright_owner', label: 'Copyright Owner', excel: 'Copyright Owner' },
      { key: 'post_title', label: 'Post Title', excel: 'Post Title' },
      { key: 'market_country', label: 'Market', excel: 'Market (Country)' },
      { key: 'seller_name_company', label: 'Seller', excel: 'Seller Name/Company' },
      { key: 'seller_country', label: 'Seller Country', excel: 'Seller Country' },
      { key: 'subscription_cost', label: 'Cost', excel: 'Subscription Cost', type: 'number' },
      { key: 'disruption_status', label: 'Disruption Status', excel: 'Disruption Status', type: 'status' },
      { key: 'removal_status', label: 'Removal Status', excel: 'Disruption Status', type: 'status' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID #' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal Date', type: 'date' },
      { key: 'tat', label: 'TAT', excel: 'TAT' },
      { key: 'additional_remarks', label: 'Remarks', excel: 'Additional Remarks/Information' },
    ]
  },

  'Marketplace': {
    table: 'marketplace',
    label: 'Marketplace',
    icon: 'fa-store',
    color: 'orange',
    uniqueUrlCol: 'marketplace_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_timestamp', label: 'Date Identified', type: 'date' },
      { key: 'platform', label: 'Platform' },
      { key: 'marketplace_url', label: 'Marketplace URL', type: 'url' },
      { key: 'iptv_brands', label: 'IPTV Brands' },
      { key: 'search_term_used', label: 'Search Term' },
      { key: 'country', label: 'Country' },
      { key: 'price', label: 'Price' },
      { key: 'seller_name', label: 'Seller Name' },
      { key: 'seller_profile', label: 'Seller Profile', type: 'url' },
      { key: 'seller_status', label: 'Seller Status' },
      { key: 'language', label: 'Language' },
      { key: 'screenshot_url', label: 'Screenshot', type: 'url' },
      { key: 'enforcement_timestamp', label: 'Enforcement Date' },
      { key: 'removal_status', label: 'Removal Status', type: 'status' },
      { key: 'removal_timestamp', label: 'Removal Date' },
      { key: 'tat', label: 'TAT' },
      { key: 'category', label: 'Category' },
    ]
  },

  'Social Media': {
    table: 'social_media',
    label: 'Social Media',
    icon: 'fa-share-nodes',
    color: 'blue',
    uniqueUrlCol: 'listing_link',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_timestamp', label: 'Date Identified', type: 'datetime' },
      { key: 'platform', label: 'Platform' },
      { key: 'listing_link', label: 'Listing URL', type: 'url' },
      { key: 'iptv_brands', label: 'IPTV Brands' },
      { key: 'iptv_brand_name', label: 'IPTV Brand Name' },
      { key: 'search_term_used', label: 'Search Term' },
      { key: 'country', label: 'Country' },
      { key: 'profile_name', label: 'Profile Name' },
      { key: 'profile_url', label: 'Profile URL', type: 'url' },
      { key: 'subscriber_count', label: 'Subscribers' },
      { key: 'views', label: 'Views' },
      { key: 'language', label: 'Language' },
      { key: 'platform_division', label: 'Platform Division' },
      { key: 'screenshot_url', label: 'Screenshot', type: 'url' },
      { key: 'enforcement_timestamp', label: 'Enforcement Date' },
      { key: 'removal_status', label: 'Removal Status', type: 'status' },
      { key: 'removal_timestamp', label: 'Removal Date' },
      { key: 'tat', label: 'TAT' },
      { key: 'category', label: 'Category' },
      { key: 'profile_channel_status', label: 'Channel Status' },
      { key: 'whatsapp_number', label: 'WhatsApp' },
    ]
  },

  'IPTV & Apps - Meta Ads': {
    table: 'iptv_apps_meta_ads',
    label: 'IPTV & Apps - Meta Ads',
    icon: 'fa-tv',
    color: 'indigo',
    uniqueUrlCol: 'source_url',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identification_date', label: 'Date', excel: 'Identification Date', type: 'datetime' },
      { key: 'type', label: 'Type', excel: 'Type' },
      { key: 'iptv_application_name', label: 'IPTV/App Name', excel: 'IPTV/Application Name' },
      { key: 'source_url', label: 'Source URL', excel: 'Source URL', type: 'url' },
      { key: 'platform', label: 'Platform', excel: 'Platform' },
      { key: 'library_id', label: 'Library ID', excel: 'Library ID' },
      { key: 'copyright_owner', label: 'Copyright Owner', excel: 'Copyright Owner' },
      { key: 'post_title', label: 'Post Title', excel: 'Post Title' },
      { key: 'market_country', label: 'Market', excel: 'Market (Country)' },
      { key: 'seller_name', label: 'Seller', excel: 'Seller Name' },
      { key: 'listing_date', label: 'Listing Date', excel: 'Listing Date', type: 'date' },
      { key: 'disruption_status', label: 'Disruption Status', excel: 'Disruption Status', type: 'status' },
      { key: 'removal_status', label: 'Removal Status', excel: 'Disruption Status', type: 'status' },
      { key: 'notice_id', label: 'Notice ID', excel: 'Notice ID #' },
      { key: 'removal_date', label: 'Removal Date', excel: 'Removal Date', type: 'date' },
      { key: 'tat', label: 'TAT', excel: 'TAT' },
      { key: 'remarks', label: 'Remarks', excel: 'Remarks' },
    ]
  },
}

export const SHEET_NAMES = Object.keys(SHEET_CONFIG)

export const SHEET_NAV = [
  { key: 'Social Media',  label: 'Social Media',  icon: 'fa-share-nodes', color: 'blue'   },
  { key: 'Marketplace',   label: 'Marketplace',   icon: 'fa-store',       color: 'orange' },
  { key: 'Unauthorized Search Result',   label: 'Unauthorized Search',       icon: 'fa-magnifying-glass', color: 'red' },
  { key: 'Ads Tutorials- Social Media',  label: 'Ads Tutorials',             icon: 'fa-bullhorn',         color: 'blue' },
  { key: 'Password Sharing-Social Med.', label: 'PW Sharing - Social',       icon: 'fa-lock',             color: 'orange' },
  { key: 'Password Sharing-Marketplace', label: 'PW Sharing - Marketplace',  icon: 'fa-cart-shopping',    color: 'purple' },
  { key: 'IPTV & Apps - Internet',       label: 'IPTV Internet',             icon: 'fa-globe',            color: 'teal' },
  { key: 'IPTV & Apps - Apps',           label: 'IPTV Apps',                 icon: 'fa-mobile-screen',    color: 'green' },
  { key: 'IPTV & Apps - Social Media',   label: 'IPTV Social Media',         icon: 'fa-share-nodes',      color: 'pink' },
  { key: 'IPTV & Apps - Marketplace',    label: 'IPTV Marketplace',          icon: 'fa-store',            color: 'yellow' },
  { key: 'IPTV & Apps - Meta Ads',       label: 'IPTV Meta Ads',             icon: 'fa-tv',               color: 'indigo' },
]

export const REMOVAL_STATUSES = [
  'Removed', 'Pending', 'Enforced', 'Not Removed',
  'Under Review', 'Appealed', 'Re-uploaded', 'Partial Removal',
  'Down', 'Up', 'Active', 'Suspended', 'Approved', 'Rejected',
]

export function getStatusBadgeClass(status) {
  if (!status) return 'badge-gray'
  const s = status.toLowerCase()
  if (s.includes('remov') || s.includes('down') || s.includes('susp') || s.includes('approv')) return 'badge-green'
  if (s.includes('pending') || s.includes('up') || s.includes('activ') || s.includes('review')) return 'badge-amber'
  if (s.includes('enforc')) return 'badge-blue'
  if (s.includes('re-upload') || s.includes('reject')) return 'badge-red'
  return 'badge-gray'
}
